# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2e6d48631f6765bb93e504f6d302d8e0ba3b3ef83fe544bfadcc47f1a644904986062aa8d762220e91c64546bf1291fc4f3aa40c15d3966b6a5d65d4a8216fc0

test:
  secret_key_base: 95e462c09a7f10de466f9f3d7835e65f674af6728512ab678f3e2f1ac7ffde52a7e2fc98cc765fda038282d509fd4578107e43c77ddcf18cd08366acfc9e06ab

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
